# Sway window rules configuration file

# --- Ventanas flotantes ---
for_window [app_id="blueman-manager"] floating enable
for_window [app_id="org.pulseaudio.pavucontrol"] floating enable
for_window [title="Volume Control"] floating enable
for_window [app_id="xed"] floating enable
for_window [title="Media viewer"] floating enable
for_window [title="Picture-in-Picture"] floating enable
for_window [app_id="Viewnior"] floating enable
for_window [title="DevTools"] floating enable
for_window [app_id="file_progress"] floating enable
for_window [app_id="confirm"] floating enable
for_window [app_id="dialog"] floating enable
for_window [app_id="download"] floating enable
for_window [app_id="notification"] floating enable
for_window [app_id="error"] floating enable
for_window [app_id="confirmreset"] floating enable
for_window [title="Open File"] floating enable
for_window [title="branchdialog"] floating enable
for_window [title="Confirm to replace files"] floating enable
for_window [title="File Operation Progress"] floating enable

# Kitty flotante (SUPER SHIFT Q)
for_window [app_id="kitty-float"] floating enable, resize set 650 400

# --- Tamaño y posición ---
for_window [title="Volume Control"] resize set 500 400
for_window [app_id="blueman-manager"] resize set 500 400
for_window [app_id="xed"] resize set 400 600


# --- Opacidad ---
for_window [app_id="blueman-manager"] opacity 0.80
for_window [app_id="org.pulseaudio.pavucontrol"] opacity 0.80
for_window [title="Volume Control"] opacity 0.80
for_window [class="Spotify"] opacity 0.80
for_window [app_id="xed"] opacity 0.80
for_window [app_id="nemo"] opacity 0.80
for_window [app_id="marktext"] opacity 0.80
for_window [app_id="md.obsidian.Obsidian"] opacity 0.80
for_window [class="steam"] opacity 0.80

# --- Layer rules (quickshell) ---
layer_effects "quickshell" {
    blur enable
    blur_xray enable
    blur_ignore_transparent enable
}
